spring:
  config:
    import: classpath:application-secret.yml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  devtools:
    restart:
      enabled: true

server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

jwt:
  secret: ThisIsASecureAndLongEnoughSecretKeyForJWTGenerationAndValidation12345
  expiration-ms: 3600000
